
- name: install updates
  yum: name=* state=latest  update_cache=yes


- name: Installing httpd
  command: yum install httpd php php-mysql -y

- name: Installing php
  command: amazon-linux-extras install -y  php7.4

