## 
- name: installing packages for all tasks(exlude wordpress)
  include_tasks: installer.yml
- name: Downloading and configuring WORDPRESS 
  include_tasks: wordpress.yml
- name: starting httpd
  include_tasks: webserver.yml

- name: restart httpd
  command: service httpd restart
 
